/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokokomputer.pelanggan;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import tokokomputer.Pengaturan.Koneksi;

/**
 *
 * @author Humaidi
 */
import javax.swing.JOptionPane;

public class PelangganView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PelangganView
     */
    public PelangganView() {
        initComponents();
        ulang();//panggil method ulang
    }
    //buat objek yang nantinya digunakn
    PreparedStatement pst; //objek pst untuk menjalankan query sql
    ResultSet rs; //objek rs untuk mengambil data dari query select
    Connection conn = new Koneksi().getKoneksi(); //agar tidak error,import kelas Koneksi
    String status, sql;//buat 2 buah variabel bertipe string

    private void tampil_data() {
        try {
            String[] judul = {"ID Pelanggan", "Nama Pelanggan", "Alamat", "No Telepon"};//judul kolom di tabel pelanggan
            DefaultTableModel dtm = new DefaultTableModel(null, judul);//import apabila erorr
            tabelPelanggan.setModel(dtm);
            if (textCari.getText().isEmpty()) {//apabila text cari kosong
                sql = "select * from tb_pelanggan"; //tampilkan semua data di table pelanggan 
            } else {
                //tampilkan data di tabel pelanggan berdasarkan nama pelanggan yang di text cari 
                sql = "select * from tb_pelanggan where nama_pelanggan like '%" + textCari.getText() + "%'";
            }
            pst = conn.prepareStatement(sql);//menjalankan query sql 
            rs = pst.executeQuery();//karena query select,ambil data menggunakan rs/resultset
            while (rs.next()) {//lakukan perulangan selama datanya ada 
                //ambil data di table pelanggan.ini menggunakan urutan kolom 
                String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                dtm.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());//import JOptionpane apabila erorr
        }
    }

    private void ulang() {
        textID.setEnabled(false);
        textNama.setEnabled(false);
        textAlamat.setEnabled(false);
        textTelpon.setEnabled(false);
        bSimpan.setEnabled(false);
        bHapus.setEnabled(false);
        bUbah.setEnabled(false);
        bTambah.setEnabled(true);
        textID.setText("");
        textNama.setText("");
        textAlamat.setText("");
        textTelpon.setText("");
        tampil_data();
    }

    private void id_otomatis() {
        try {
            //query mengambil id pelanggan terakhir
            sql = "select id_pelanggan from tb_pelanggan order by id_pelanggan desc limit 1";
            pst = conn.prepareStatement(sql);//menjalankan query sql
            rs = pst.executeQuery();//query select, maka ambil datanya menggunakan rs/resultset
            if (rs.next()) {//jika data dari query di atas ada
                //ambil id pelanggan terakhir kemudian substring(4):ambil huruf dari index ke 4 lalu di tambah 1 
                int kode;
                kode = Integer.parseInt(rs.getString(1).substring(4)) + 1;
                textID.setText("PLG-" + kode);//tambahkan id pelanggan dengan format:PLG-(nilai Kode)
            } else {
                //apabila data pelanggan kosong ,maka id pelanggan pertama adalah PLG-1000
                textID.setText("PLG-1000");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        textTelpon = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bUlang = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        textCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Form Pelanggan");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("FORM PELANGGAN");

        jLabel2.setText("ID PELANGGAN");

        jLabel3.setText("NAMA PELANGGAN");

        jLabel4.setText("ALAMAT");

        jLabel5.setText("NO TELPON");

        jLabel6.setText("CARI PELANGGAN");

        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setText("UBAH");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bUlang.setText("ULANG");
        bUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUlangActionPerformed(evt);
            }
        });

        bKeluar.setText("KELUAR");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        textCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCariKeyReleased(evt);
            }
        });

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelanggan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAlamat)
                            .addComponent(textNama)
                            .addComponent(textTelpon)
                            .addComponent(textCari)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bHapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bUbah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bUlang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bKeluar)))
                                .addGap(0, 54, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(bSimpan)
                    .addComponent(bHapus)
                    .addComponent(bUbah)
                    .addComponent(bUlang)
                    .addComponent(bKeluar))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        textID.setEnabled(false);
        textNama.setEnabled(true);
        textAlamat.setEnabled(true);
        textTelpon.setEnabled(true);
        bTambah.setEnabled(false);
        bSimpan.setEnabled(true);
        status = "tambah";
        id_otomatis();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        //minta komfirmasi sebelum di menghapus untuk komfirrmasi gunakan showComfirmDialog
        int konf = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus pelanggan ini?",
                "Hapus data?", JOptionPane.YES_NO_OPTION);//kalian ketik dalam 1 baris saja 
        if (konf == 0) {                //jika dipilih yes saat komfirmasi 
            try {
                //jalankan perintah delete untuk menghapus data
                pst = conn.prepareStatement("delete from tb_pelanggan where id_pelanggan =?");
                pst.setString(1, textID.getText());
                pst.executeUpdate();//eksekusi/jalankan query delete
                JOptionPane.showMessageDialog(null, "data pelanggan berhasil dihapus!");
                ulang();//panggil method ulang
            } catch (SQLException ex) {
                //menampilkan message box apabila proses hapus data gagal
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        }

    }//GEN-LAST:event_bHapusActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        textID.setEnabled(false);
        textNama.setEnabled(true);
        textAlamat.setEnabled(true);
        textTelpon.setEnabled(true);
        bUbah.setEnabled(false);
        bSimpan.setEnabled(true);
        bHapus.setEnabled(false);
        status = "ubah";
    }//GEN-LAST:event_bUbahActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        //mencek isi textfield/validasi
        if (textAlamat.getText().isEmpty() || textNama.getText().isEmpty() || textTelpon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Inputan ada yang belum di isi!");
        } else {
            try {
                if (status.equals("tambah")) {//jika variabel status nilainya adalah tambah
                    //lakukan penambahan data/gunakan query insert
                    sql = "insert into tb_pelanggan values(?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, textID.getText());//angka 1 merujuk ke tanda tanya petama (parameter pertama) baris 315
                    pst.setString(2, textNama.getText());//angka 2 merujuk ke tanda tanya petama (parameter pertama) baris 315
                    pst.setString(3, textAlamat.getText());//angka 3 merujuk ke tanda tanya petama (parameter pertama) baris 315
                    pst.setString(4, textTelpon.getText());//angka 4 merujuk ke tanda tanya petama (parameter pertama) baris 315
                } else if (status.equals("ubah")) {//jika variabel status nilainya adalah ubah
                    sql = "update tb_pelanggan set nama_pelanggan=?,alamat=?,no_telepon=?where id_pelanggan=?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, textNama.getText());
                    pst.setString(2, textAlamat.getText());
                    pst.setString(3, textTelpon.getText());
                    pst.setString(4, textID.getText());
                }
                pst.executeUpdate();//jalankan atau eksekusi query
                JOptionPane.showMessageDialog(null, "Data pelanggan berhasil di tambahkan");
                ulang();//panggil method ulang
            } catch (SQLException e) {
                //menampilkan message boxapabila proses simpan data gagal
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUlangActionPerformed
        ulang();
    }//GEN-LAST:event_bUlangActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void textCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCariKeyReleased
        tampil_data();
    }//GEN-LAST:event_textCariKeyReleased

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        int baris = tabelPelanggan.getSelectedRow();//untuk mengetahui baris mana yang di klik 
        String id = tabelPelanggan.getValueAt(baris, 0).toString();//ambil nilai dari kolom 0 pada tabel pelanggan yang di klik
        if (!id.isEmpty()) {//jika variabel id tidak kosong
            textID.setText(id);//tampilkan variabel id ke textID
            textNama.setText(tabelPelanggan.getValueAt(baris, 1).toString());//tampilkan nilai kolom 1(nama) di tabelPelanggan
            textAlamat.setText(tabelPelanggan.getValueAt(baris, 2).toString());//tampilkan nilai kolom 2(alamat) di tabelPelanggan
            textTelpon.setText(tabelPelanggan.getValueAt(baris, 3).toString());//tampilkan nilai kolom 3(no_telpon) di tabelPelanggan
            bTambah.setEnabled(false);//menonaktifkan button tambah
            bSimpan.setEnabled(false);//menonaktifkan button simpan
            bHapus.setEnabled(true);//menonaktifkan button hapus
            bUbah.setEnabled(true);//menonaktifkan button Ubah
        }
    }//GEN-LAST:event_tabelPelangganMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JButton bUlang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textCari;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textTelpon;
    // End of variables declaration//GEN-END:variables
}
