/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokokomputer.barang;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import tokokomputer.Pengaturan.Koneksi;
import javax.swing.JOptionPane;
import tokokomputer.transaksi.TransaksiView;

/**
 *
 * @author Humaidi
 */
public class BarangView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BarangView
     */
    public BarangView() {
        initComponents();
        ulang();
    }
    PreparedStatement pst; //objek pst untuk menjalankan query sql
    ResultSet rs; //objek rs untuk mengambil data dari query select
    Connection conn = new Koneksi().getKoneksi(); //agar tidak error,import kelas Koneksi
    String status,sql;//buat 2 buah variabel bertipe string
    
    private void tampil_data(){
        try{
            String[] judul = {"Kode Barang","Nama Barang","Kategori","Harga","Stok"};
            DefaultTableModel dtm = new DefaultTableModel(null,judul);
            tabelBarang.setModel(dtm);
            if(textCari.getText().isEmpty()){
            sql="select * from tb_barang";
            }else{
                sql = "select * from tb_barang where nama_barang like '%"+ textCari.getText()+"%'";
            }
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String[]data ={rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),rs.getString(5)};
                dtm.addRow(data);
            }
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    
    private void ulang(){
    textKode.setEnabled(false);
    textNama.setEnabled(false);
    textKategori.setEnabled(false);
    textHarga.setEnabled(false);
    textStok.setEnabled(false);
    bSimpan.setEnabled(false);
    bHapus.setEnabled(false);
    bUbah.setEnabled(false);
    bTambah.setEnabled(true);
    textKode.setText("");
    textNama.setText("");
    textKategori.setText("");
    textHarga.setText("");
    textStok.setText("");
    tampil_data();
    }
    
    private void id_otomatis(){
    try{
        sql="select kode_barang from tb_barang order by kode_barang desc limit 1";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){ 
        int kode;
            kode = Integer.parseInt(rs.getString(1).substring(4))+1;
        textKode.setText("BRG-"+kode);
        }else{
            textKode.setText("BRG-1000");
        }
    }catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textKode = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textKategori = new javax.swing.JTextField();
        textHarga = new javax.swing.JTextField();
        textStok = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bUlang = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Form Barang");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("FORM BARANG");

        jLabel2.setText("KODE BARANG");

        jLabel3.setText("NAMA BARANG");

        jLabel4.setText("KATEGORI");

        jLabel5.setText("HARGA");

        jLabel6.setText("STOK");

        textKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKodeActionPerformed(evt);
            }
        });

        textKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKategoriActionPerformed(evt);
            }
        });

        textHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHargaActionPerformed(evt);
            }
        });

        textStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStokActionPerformed(evt);
            }
        });

        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setText("UBAH");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bUlang.setText("ULANG");
        bUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUlangActionPerformed(evt);
            }
        });

        bKeluar.setText("KELUAR");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        jLabel7.setText("CARI BARANG");

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        tabelBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelBarangKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bTambah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bHapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bUbah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bUlang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bKeluar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(textKode, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168))
                                    .addComponent(textStok)
                                    .addComponent(textHarga)
                                    .addComponent(textKategori)
                                    .addComponent(textNama)
                                    .addComponent(textCari)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(bSimpan)
                    .addComponent(bHapus)
                    .addComponent(bUbah)
                    .addComponent(bUlang)
                    .addComponent(bKeluar))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        if(textKategori.getText().isEmpty() || textNama.getText().isEmpty() || textHarga.getText().isEmpty() || textStok.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Inputan ada yang belum di isi!");
        }else{
        try{
        if(status.equals("tambah")){
        sql="insert into tb_barang values(?,?,?,?,?)";
        pst=conn.prepareStatement(sql);
        pst.setString(1,textKode.getText());
        pst.setString(2,textNama.getText());
        pst.setString(3,textKategori.getText());
        pst.setString(4,textHarga.getText());
        pst.setString(5,textStok.getText());
        }else if(status.equals("ubah")){
            sql="update tb_barang set nama_barang=?,kategori=?,harga=?,stok=? where kode_barang=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,textNama.getText());
            pst.setString(2,textKategori.getText());
            pst.setString(3,textHarga.getText());
            pst.setString(4,textStok.getText());
            pst.setString(5,textKode.getText());
        }
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Barang berhasil di tambahkan");
        ulang();
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
        }
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        //minta komfirmasi sebelum di menghapus untuk konfirmasi gunakan showComfirmDialog
        int konf=JOptionPane.showConfirmDialog(null,"Yakin ingin menghapus pelanggan ini?",
                "Hapus data?",JOptionPane.YES_NO_OPTION);//kalian ketik dalam 1 baris saja 
        if(konf==0){                //jika dipilih yes saat komfirmasi 
            try {
                //jalankan perintah delete untuk menghapus data
                pst=conn.prepareStatement("delete from tb_barang where kode_barang=?");
                pst.setString(1,textKode.getText());
                pst.executeUpdate();//eksekusi/jalankan query delete
                JOptionPane.showMessageDialog(null, "data pelanggan berhasil dihapus!");
                ulang();//panggil method ulang
            }catch(SQLException ex){
                //menampilkan message box apabila proses hapus data gagal
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void textKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKodeActionPerformed

    private void textKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKategoriActionPerformed

    private void textHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHargaActionPerformed

    private void textStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStokActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
      textKode.setEnabled(false);
      textNama.setEnabled(true);
      textKategori.setEnabled(true);
      textHarga.setEnabled(true);
      textStok.setEnabled(true);
      bTambah.setEnabled(false);
      bSimpan.setEnabled(true);
      status="tambah";
      id_otomatis();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
      textKode.setEnabled(false);
      textNama.setEnabled(true);
      textKategori.setEnabled(true);
      textHarga.setEnabled(true);
      textStok.setEnabled(true);
      bUbah.setEnabled(false);
      bSimpan.setEnabled(true);
      bHapus.setEnabled(false);
      status="ubah";
    }//GEN-LAST:event_bUbahActionPerformed

    private void bUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUlangActionPerformed
        ulang();
    }//GEN-LAST:event_bUlangActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void tabelBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelBarangKeyReleased
        tampil_data();
    }//GEN-LAST:event_tabelBarangKeyReleased

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        int baris=tabelBarang.getSelectedRow();
        String id=tabelBarang.getValueAt(baris,0).toString();
        if(!id.isEmpty()){
            TransaksiView.textKodeBarang.setText(id);
            TransaksiView.textNamaBarang.setText(tabelBarang.getValueAt(baris, 1).toString());
            TransaksiView.textKategori.setText(tabelBarang.getValueAt(baris, 2).toString());
            TransaksiView.textHarga.setText(tabelBarang.getValueAt(baris, 3).toString());
            TransaksiView.textStok.setText(tabelBarang.getValueAt(baris, 4).toString());
            bTambah.setEnabled(false);
            bSimpan.setEnabled(false);
            bHapus.setEnabled(false);
            bUbah.setEnabled(true);
        }
    }//GEN-LAST:event_tabelBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JButton bUlang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTextField textCari;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textKategori;
    private javax.swing.JTextField textKode;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textStok;
    // End of variables declaration//GEN-END:variables
}
